### ISSUE TITLE
Peer-to-peer

### ISSUE THREAD

**Issue by George7h** [newtonah0/Awesome-books#5]
Hi @newtonah0,

Great job on your project so far!!!! 👍 💯 🥇 

Highlights: 🟢 

- Great functionality 🔢 
- Extremely similar to the framework given. 🪟 

However here are a few suggestions for your project: ✍️ 

- In your readme file - You can say "npm install" to install all modules from the JSON package.

- The FAQ can be removed from the readme as well.

- Here are some guidelines to deploy your project from the dis folder:
https://javascript.plainenglish.io/deploying-any-app-to-github-pages-1e8e946bf890
or 
deploy the project from the latest branch and add the "dist" folder path to the link. However, I do prefer first above suggestion.

<img src="https://media3.giphy.com/media/d31w24psGYeekCZy/giphy.gif"/>

The above suggestions will make a review easier and also will make your project look more presentable.

But overall great job!!! 😁 🥳

**Comment by m00h0** [comment]
Thanks @George7h I deploy my project.
